import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Amazing Bunch Unisex Salon",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </head> */}
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
