import Footer from "./components/Footer";
import "./globals.css";

export const metadata = {
  title: "Amazing Bunch Unisex Salon",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
